export const HEART_ICON_COLOR = '#414141';
export const HEART_ICON_COLOR_SELECTED = '#2699FB';

export const BUTTON_EMAIL_COLOR = '#5ADAFD';
export const BUTTON_LOGIN_COLOR = '#5ADAFD';
export const BUTTON_FACEBOOK_COLOR = '#4267B2';
export const BUTTON_REGISTER_COLOR = '#5ADAFD';

export const BUTTON_LOADMORE_COLOR = '#5ADAFD';
